/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import projeto.DadosDaCompra;

/**
 *
 * @author italo
 */
public class TelaDeCompra extends javax.swing.JPanel {
    
    private String origem;
    private String destino;
    private String dataCompra;
    private String nome;
    private String RG;
    private String dataNascimento;
    private String poltrona;

    /**
     * Creates new form TelaDeCompra
     */
    public TelaDeCompra() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destino_jComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        origem_jComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dataCompra_jTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nome_jTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rg_jTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataNascimento_jTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valor_jTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        poltrona_jTextField = new javax.swing.JTextField();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 700));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p01green.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverEnabled(true);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p01blue.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(805, 120, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p02green.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverEnabled(true);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p02blue.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(840, 120, 30, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p03green.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setRolloverEnabled(true);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p03blue.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(965, 120, 30, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p04green.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setRolloverEnabled(true);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p04blue.png"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(930, 120, 30, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p05green.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setRolloverEnabled(true);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p05blue.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(805, 160, 30, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p06green.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setRolloverEnabled(true);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p06blue.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(840, 160, 30, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p07green.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setRolloverEnabled(true);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p07blue.png"))); // NOI18N
        jPanel1.add(jButton7);
        jButton7.setBounds(965, 160, 30, 30);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p08green.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setRolloverEnabled(true);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p08blue.png"))); // NOI18N
        jPanel1.add(jButton8);
        jButton8.setBounds(930, 160, 30, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p09green.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.setRolloverEnabled(true);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p09blue.png"))); // NOI18N
        jPanel1.add(jButton9);
        jButton9.setBounds(805, 200, 30, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p10green.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setRolloverEnabled(true);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p10blue.png"))); // NOI18N
        jPanel1.add(jButton10);
        jButton10.setBounds(840, 200, 30, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p11green.png"))); // NOI18N
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRolloverEnabled(true);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p11blue.png"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(965, 200, 30, 30);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p12green.png"))); // NOI18N
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.setRolloverEnabled(true);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p12blue.png"))); // NOI18N
        jPanel1.add(jButton12);
        jButton12.setBounds(930, 200, 30, 30);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p13green.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.setRolloverEnabled(true);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p13blue.png"))); // NOI18N
        jPanel1.add(jButton13);
        jButton13.setBounds(805, 240, 30, 30);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p14green.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusPainted(false);
        jButton14.setRolloverEnabled(true);
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p14blue.png"))); // NOI18N
        jPanel1.add(jButton14);
        jButton14.setBounds(840, 240, 30, 30);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p15green.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.setRolloverEnabled(true);
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p15blue.png"))); // NOI18N
        jPanel1.add(jButton15);
        jButton15.setBounds(965, 240, 30, 30);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p16green.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jButton16.setRolloverEnabled(true);
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p16blue.png"))); // NOI18N
        jPanel1.add(jButton16);
        jButton16.setBounds(930, 240, 30, 30);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p17green.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setFocusPainted(false);
        jButton17.setRolloverEnabled(true);
        jButton17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p17blue.png"))); // NOI18N
        jPanel1.add(jButton17);
        jButton17.setBounds(805, 280, 30, 30);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p18green.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setFocusPainted(false);
        jButton18.setRolloverEnabled(true);
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p18blue.png"))); // NOI18N
        jPanel1.add(jButton18);
        jButton18.setBounds(840, 280, 30, 30);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p19green.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setFocusPainted(false);
        jButton19.setRolloverEnabled(true);
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p19blue.png"))); // NOI18N
        jPanel1.add(jButton19);
        jButton19.setBounds(965, 280, 30, 30);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p20green.png"))); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setFocusPainted(false);
        jButton20.setRolloverEnabled(true);
        jButton20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p20blue.png"))); // NOI18N
        jPanel1.add(jButton20);
        jButton20.setBounds(930, 280, 30, 30);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p21green.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setFocusPainted(false);
        jButton21.setRolloverEnabled(true);
        jButton21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p21blue.png"))); // NOI18N
        jPanel1.add(jButton21);
        jButton21.setBounds(805, 320, 30, 30);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p22green.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setFocusPainted(false);
        jButton22.setRolloverEnabled(true);
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p22blue.png"))); // NOI18N
        jPanel1.add(jButton22);
        jButton22.setBounds(840, 320, 30, 30);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p23green.png"))); // NOI18N
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setFocusPainted(false);
        jButton23.setRolloverEnabled(true);
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p23blue.png"))); // NOI18N
        jPanel1.add(jButton23);
        jButton23.setBounds(965, 320, 30, 30);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p24green.png"))); // NOI18N
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setFocusPainted(false);
        jButton24.setRolloverEnabled(true);
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p24blue.png"))); // NOI18N
        jPanel1.add(jButton24);
        jButton24.setBounds(930, 320, 30, 30);

        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p25green.png"))); // NOI18N
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setFocusPainted(false);
        jButton25.setRolloverEnabled(true);
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p25blue.png"))); // NOI18N
        jPanel1.add(jButton25);
        jButton25.setBounds(805, 360, 30, 30);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p26green.png"))); // NOI18N
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setFocusPainted(false);
        jButton26.setRolloverEnabled(true);
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p26blue.png"))); // NOI18N
        jPanel1.add(jButton26);
        jButton26.setBounds(840, 360, 30, 30);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p27green.png"))); // NOI18N
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setFocusPainted(false);
        jButton27.setRolloverEnabled(true);
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p27blue.png"))); // NOI18N
        jPanel1.add(jButton27);
        jButton27.setBounds(965, 360, 30, 30);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p28green.png"))); // NOI18N
        jButton28.setBorderPainted(false);
        jButton28.setContentAreaFilled(false);
        jButton28.setFocusPainted(false);
        jButton28.setRolloverEnabled(true);
        jButton28.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p28blue.png"))); // NOI18N
        jPanel1.add(jButton28);
        jButton28.setBounds(930, 360, 30, 30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p29green.png"))); // NOI18N
        jButton29.setBorderPainted(false);
        jButton29.setContentAreaFilled(false);
        jButton29.setFocusPainted(false);
        jButton29.setRolloverEnabled(true);
        jButton29.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p29blue.png"))); // NOI18N
        jPanel1.add(jButton29);
        jButton29.setBounds(805, 400, 30, 30);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p30green.png"))); // NOI18N
        jButton30.setBorderPainted(false);
        jButton30.setContentAreaFilled(false);
        jButton30.setFocusPainted(false);
        jButton30.setRolloverEnabled(true);
        jButton30.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p30blue.png"))); // NOI18N
        jPanel1.add(jButton30);
        jButton30.setBounds(840, 400, 30, 30);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p31green.png"))); // NOI18N
        jButton31.setBorderPainted(false);
        jButton31.setContentAreaFilled(false);
        jButton31.setFocusPainted(false);
        jButton31.setRolloverEnabled(true);
        jButton31.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p31blue.png"))); // NOI18N
        jPanel1.add(jButton31);
        jButton31.setBounds(965, 400, 30, 30);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p32green.png"))); // NOI18N
        jButton32.setBorderPainted(false);
        jButton32.setContentAreaFilled(false);
        jButton32.setFocusPainted(false);
        jButton32.setRolloverEnabled(true);
        jButton32.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p32blue.png"))); // NOI18N
        jPanel1.add(jButton32);
        jButton32.setBounds(930, 400, 30, 30);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p33green.png"))); // NOI18N
        jButton33.setBorderPainted(false);
        jButton33.setContentAreaFilled(false);
        jButton33.setFocusPainted(false);
        jButton33.setRolloverEnabled(true);
        jButton33.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p33blue.png"))); // NOI18N
        jPanel1.add(jButton33);
        jButton33.setBounds(805, 440, 30, 30);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p34green.png"))); // NOI18N
        jButton34.setBorderPainted(false);
        jButton34.setContentAreaFilled(false);
        jButton34.setFocusPainted(false);
        jButton34.setRolloverEnabled(true);
        jButton34.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p34blue.png"))); // NOI18N
        jPanel1.add(jButton34);
        jButton34.setBounds(840, 440, 30, 30);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p35green.png"))); // NOI18N
        jButton35.setBorderPainted(false);
        jButton35.setContentAreaFilled(false);
        jButton35.setFocusPainted(false);
        jButton35.setRolloverEnabled(true);
        jButton35.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p35blue.png"))); // NOI18N
        jPanel1.add(jButton35);
        jButton35.setBounds(965, 440, 30, 30);

        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p36green.png"))); // NOI18N
        jButton36.setBorderPainted(false);
        jButton36.setContentAreaFilled(false);
        jButton36.setFocusPainted(false);
        jButton36.setRolloverEnabled(true);
        jButton36.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p36blue.png"))); // NOI18N
        jPanel1.add(jButton36);
        jButton36.setBounds(930, 440, 30, 30);

        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p37green.png"))); // NOI18N
        jButton37.setBorderPainted(false);
        jButton37.setContentAreaFilled(false);
        jButton37.setFocusPainted(false);
        jButton37.setRolloverEnabled(true);
        jButton37.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p37blue.png"))); // NOI18N
        jPanel1.add(jButton37);
        jButton37.setBounds(805, 480, 30, 30);

        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p38green.png"))); // NOI18N
        jButton38.setBorderPainted(false);
        jButton38.setContentAreaFilled(false);
        jButton38.setFocusPainted(false);
        jButton38.setRolloverEnabled(true);
        jButton38.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p38blue.png"))); // NOI18N
        jPanel1.add(jButton38);
        jButton38.setBounds(840, 480, 30, 30);

        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p39green.png"))); // NOI18N
        jButton39.setBorderPainted(false);
        jButton39.setContentAreaFilled(false);
        jButton39.setFocusPainted(false);
        jButton39.setRolloverEnabled(true);
        jButton39.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p39blue.png"))); // NOI18N
        jPanel1.add(jButton39);
        jButton39.setBounds(965, 480, 30, 30);

        jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p40green.png"))); // NOI18N
        jButton40.setBorderPainted(false);
        jButton40.setContentAreaFilled(false);
        jButton40.setFocusPainted(false);
        jButton40.setRolloverEnabled(true);
        jButton40.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p40blue.png"))); // NOI18N
        jPanel1.add(jButton40);
        jButton40.setBounds(930, 480, 30, 30);

        jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p41green.png"))); // NOI18N
        jButton41.setBorderPainted(false);
        jButton41.setContentAreaFilled(false);
        jButton41.setFocusPainted(false);
        jButton41.setRolloverEnabled(true);
        jButton41.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p41blue.png"))); // NOI18N
        jPanel1.add(jButton41);
        jButton41.setBounds(805, 520, 30, 30);

        jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p42green.png"))); // NOI18N
        jButton42.setBorderPainted(false);
        jButton42.setContentAreaFilled(false);
        jButton42.setFocusPainted(false);
        jButton42.setRolloverEnabled(true);
        jButton42.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p42blue.png"))); // NOI18N
        jPanel1.add(jButton42);
        jButton42.setBounds(840, 520, 30, 30);

        jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p43green.png"))); // NOI18N
        jButton43.setBorderPainted(false);
        jButton43.setContentAreaFilled(false);
        jButton43.setFocusPainted(false);
        jButton43.setRolloverEnabled(true);
        jButton43.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p43blue.png"))); // NOI18N
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);
        jButton43.setBounds(965, 520, 30, 30);

        jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p44green.png"))); // NOI18N
        jButton44.setBorderPainted(false);
        jButton44.setContentAreaFilled(false);
        jButton44.setFocusPainted(false);
        jButton44.setRolloverEnabled(true);
        jButton44.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p44blue.png"))); // NOI18N
        jPanel1.add(jButton44);
        jButton44.setBounds(930, 520, 30, 30);

        jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p45green.png"))); // NOI18N
        jButton45.setBorderPainted(false);
        jButton45.setContentAreaFilled(false);
        jButton45.setFocusPainted(false);
        jButton45.setRolloverEnabled(true);
        jButton45.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p45blue.png"))); // NOI18N
        jPanel1.add(jButton45);
        jButton45.setBounds(805, 560, 30, 30);

        jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p46green.png"))); // NOI18N
        jButton46.setBorderPainted(false);
        jButton46.setContentAreaFilled(false);
        jButton46.setFocusPainted(false);
        jButton46.setRolloverEnabled(true);
        jButton46.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p46blue.png"))); // NOI18N
        jPanel1.add(jButton46);
        jButton46.setBounds(840, 560, 30, 30);

        jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p47green.png"))); // NOI18N
        jButton47.setBorderPainted(false);
        jButton47.setContentAreaFilled(false);
        jButton47.setFocusPainted(false);
        jButton47.setRolloverEnabled(true);
        jButton47.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p47blue.png"))); // NOI18N
        jPanel1.add(jButton47);
        jButton47.setBounds(965, 560, 30, 30);

        jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p48green.png"))); // NOI18N
        jButton48.setBorderPainted(false);
        jButton48.setContentAreaFilled(false);
        jButton48.setFocusPainted(false);
        jButton48.setRolloverEnabled(true);
        jButton48.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p48blue.png"))); // NOI18N
        jPanel1.add(jButton48);
        jButton48.setBounds(930, 560, 30, 30);

        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p49green.png"))); // NOI18N
        jButton49.setBorderPainted(false);
        jButton49.setContentAreaFilled(false);
        jButton49.setFocusPainted(false);
        jButton49.setRolloverEnabled(true);
        jButton49.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p49blue.png"))); // NOI18N
        jPanel1.add(jButton49);
        jButton49.setBounds(805, 600, 30, 30);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p50green.png"))); // NOI18N
        jButton50.setBorderPainted(false);
        jButton50.setContentAreaFilled(false);
        jButton50.setFocusPainted(false);
        jButton50.setRolloverEnabled(true);
        jButton50.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/p50blue.png"))); // NOI18N
        jPanel1.add(jButton50);
        jButton50.setBounds(840, 600, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b12.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 10, 210, 660);

        jLabel2.setText("NOME DA EMPRESA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 320, 80);

        destino_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João Pessoa - PB", "São Paulo - SP", "Salvador - BA", "Rio de Janeiro - RJ", "Recife - PE" }));
        destino_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destino_jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(destino_jComboBox);
        destino_jComboBox.setBounds(210, 140, 160, 25);

        jLabel3.setText("DESTINO:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 120, 70, 15);

        jLabel4.setText("ORIGEM:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 70, 15);

        origem_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João Pessoa - PB", "São Paulo - SP", "Salvador - BA", "Rio de Janeiro - RJ", "Recife - PE" }));
        origem_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origem_jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(origem_jComboBox);
        origem_jComboBox.setBounds(30, 140, 160, 25);

        jLabel5.setText("DATA:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 120, 41, 15);

        dataCompra_jTextField.setText("dd/mm/aaaa");
        dataCompra_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCompra_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dataCompra_jTextField);
        dataCompra_jTextField.setBounds(390, 140, 100, 23);

        jLabel6.setText("NOME: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 280, 50, 15);

        nome_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nome_jTextField);
        nome_jTextField.setBounds(30, 300, 460, 23);

        jLabel7.setText("RG:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 330, 24, 15);

        rg_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rg_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(rg_jTextField);
        rg_jTextField.setBounds(30, 350, 160, 23);

        jLabel8.setText("DATA NASCIMENTO:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 330, 150, 15);

        dataNascimento_jTextField.setText("dd/mm/aaaa");
        dataNascimento_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimento_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dataNascimento_jTextField);
        dataNascimento_jTextField.setBounds(210, 350, 140, 23);

        jLabel9.setText("VALOR:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 190, 51, 15);

        valor_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(valor_jTextField);
        valor_jTextField.setBounds(30, 210, 70, 23);

        jLabel10.setText("POLTRONA:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(210, 190, 90, 15);

        poltrona_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poltrona_jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(poltrona_jTextField);
        poltrona_jTextField.setBounds(210, 210, 80, 23);

        jButton51.setText("Salvar Dados");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton51);
        jButton51.setBounds(30, 430, 160, 31);

        jButton52.setText("Cancelar");
        jPanel1.add(jButton52);
        jButton52.setBounds(230, 430, 98, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void destino_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destino_jComboBoxActionPerformed
        //Captura a destino       
        
        destino = destino_jComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_destino_jComboBoxActionPerformed

    private void origem_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origem_jComboBoxActionPerformed
        //Captura a origem       
        
        origem = origem_jComboBox.getSelectedItem().toString();
        
        System.out.println("origem: "+ origem);
    }//GEN-LAST:event_origem_jComboBoxActionPerformed

    private void dataCompra_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCompra_jTextFieldActionPerformed
        //Captura a data da compra
        //dataCompra = dataCompra_jTextField.getText();
    }//GEN-LAST:event_dataCompra_jTextFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void rg_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rg_jTextFieldActionPerformed
        // Captura o RG        
        //RG = rg_jTextField.getText().toString();
    }//GEN-LAST:event_rg_jTextFieldActionPerformed

    private void dataNascimento_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimento_jTextFieldActionPerformed
        // Captura a data de nascimento
        //dataNascimento = dataNascimento_jTextField.getText().toString();
    }//GEN-LAST:event_dataNascimento_jTextFieldActionPerformed

    private void valor_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_jTextFieldActionPerformed
        // Captura o valor da passagem
        
        
    }//GEN-LAST:event_valor_jTextFieldActionPerformed

    private void poltrona_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poltrona_jTextFieldActionPerformed
        // Captura o numero da poltrona
        
    }//GEN-LAST:event_poltrona_jTextFieldActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // Salva os dados contidos nas caixas de dialogo
        
        //Captura a data da compra
        dataCompra = dataCompra_jTextField.getText();        
        // Captura a Poltrona
        poltrona = poltrona_jTextField.getText();
        // Captura o nome        
        nome = nome_jTextField.getText();
        // Captura o RG        
        RG = rg_jTextField.getText();
        // Captura a data de nascimento
        dataNascimento = dataNascimento_jTextField.getText();
        
        // Um objeto dados e imprime just check!
        DadosDaCompra dados = new DadosDaCompra(origem, destino, dataCompra, nome, RG, dataNascimento, poltrona);
        System.out.println("Origem: " + origem);
        System.out.println("Destino: " + destino);
        System.out.println("Data: " + dataCompra);
        System.out.println("Nome: " + nome);
        System.out.println("RG: " + RG);
        System.out.println("Nascimento: " + dataNascimento);
        System.out.println("Poltrona: " + poltrona);
        
    }//GEN-LAST:event_jButton51ActionPerformed

    private void nome_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_jTextFieldActionPerformed
        // Captura o nome        
        //nome = nome_jTextField.getText().toString();
    }//GEN-LAST:event_nome_jTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dataCompra_jTextField;
    private javax.swing.JTextField dataNascimento_jTextField;
    private javax.swing.JComboBox<String> destino_jComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_jTextField;
    private javax.swing.JComboBox<String> origem_jComboBox;
    private javax.swing.JTextField poltrona_jTextField;
    private javax.swing.JTextField rg_jTextField;
    private javax.swing.JTextField valor_jTextField;
    // End of variables declaration//GEN-END:variables
}